name: ticket
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.1+1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  simple_animations: ^4.2.0
  hive_flutter: ^1.1.0
  flutter_screenutil:
  isar: ^3.0.2
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  flutter_easyloading: ^3.0.5
  isar_flutter_libs: ^3.0.2
  flutter_svg: ^1.1.6
  bloc_concurrency: ^0.2.0
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  flutter_modular: ^5.0.3

  uuid: ^3.0.7
  logger: ^2.0.1
  bot_toast: ^4.0.3
  flutter_gen: ^5.2.0
  super_rich_text: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.2
  build_runner: ^2.3.2
  flutter_gen_runner:




flutter:

  assets:
    - assets/color/
    - assets/images/
    - assets/images/icons/
    - assets/languages/


#flutter_icons:
#  image_path: "assets/images/img.png"
#  android: true
#  ios: true

flutter_gen:
  output: lib/core/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml


  uses-material-design: true


